### ISSUE TITLE
Find out why BBBC023 is missing and re-add it

### ISSUE THREAD

**Issue by N3llz** [broadinstitute/imaging-bbbc#2]
BBBC023 did not get added when we created a new repo
- [ ] find out why
- [ ] re-add BBBC (see [README](https://github.com/broadinstitute/imaging-bbbc/blob/master/README.md#adding-a-new-dataset) for instructions on how to do so)

**Comment by shntnu** [comment]
Same as #67: 

This is among the many profiling projects that are [listed](https://airtable.com/appctUGldmRNkVS19/tblXX3mTxhCR9Bxbq/viwNJfGOOJot7Wr3x/rechM3NmzVCx73w8G?blocks=hide) in the Airtable, which would eventually be listed in https://github.com/broadinstitute/cellpainting-gallery

BBBC023 is not referred to anywhere, including the BBBC website, nor anywhere on the web (I googled it). It is referred to in a few documents in GDrive, but none actually requiring that it exists

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/1210428/179354030-fdb6aec9-6b6f-4976-b6ed-d6cd3c9586e0.png">

I'll therefore close this issue
