### ISSUE TITLE
Create a new dataset for Clonal variation project

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/imaging-bbbc#67]
The Cell Painting data from this paper
https://www.nature.com/articles/s41586-018-0409-3

Project on S3 is here:
2017_06_26_Clonal_Variation_Golub_lab-Uri_Ben-David_Broad

1 plate of data, 27 MCF7 strains 

[PlateMap_AU00027623.txt](https://github.com/broadinstitute/imaging-bbbc/files/2856259/PlateMap_AU00027623.txt)

**Comment by bledford87** [comment]
@bethac07 Looks like you're an author on this paper. Do you have enough info to fill out the Google form on the [Contribute page](https://bbbc.broadinstitute.org/contribute) so I can get this updated?

**Comment by bethac07** [comment]
Yup, will do (would need to look a few things up, will do it this week).

**Comment by shntnu** [comment]
This is among the many profiling projects that are [listed](https://airtable.com/appctUGldmRNkVS19/tblXX3mTxhCR9Bxbq/viwNJfGOOJot7Wr3x/rechM3NmzVCx73w8G?blocks=hide) in the Airtable, which would eventually be listed in https://github.com/broadinstitute/cellpainting-gallery

I'll therefore close this issue but Beth can reopen if needed
