### ISSUE TITLE
Add a note about selection of BBBC021 compounds

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/imaging-bbbc#81]
A subset of the compound-concentrations have been identified as clearly having one of 12 different primary mechanisms of action. Mechanistic classes were selected so as to represent a wide cross-section of cellular morphological phenotypes. The differences between phenotypes in some cases were very subtle: we identified 6 of the 12 mechanisms visually (Actin disruptors, Aurora kinase inhibitors, Eg5 inhibitors, Microtubule destabilizers, Microtubule stabilizers, and Epithelial); the remainder were defined based on the literature. 

All compounds were tested at eight doses. The top concentration was different for many of the compounds and was carefully selected from the literature. Not all concentrations are available in this dataset. Missing concentrations are due to one of three factors:
- The dose was determined to be inactive. Activity was defined by setting a threshold on the Mahalanobis distance from the set of DMSO profiles: profiles of doses that were outside this threshold were considered active. The feature space corresponded to measurements extracted by a proprietary software tool used at AstraZeneca.
- The dose was determined to be overly toxic, i.e., the images had no cells or very few cells.
- The images did not pass QC, that is, they were either out of focus wells or contained image artifacts.

**Comment by bledford87** [comment]
Added!
