### ISSUE TITLE
Update Contribute and Index pages

### ISSUE THREAD

**Issue by N3llz** [broadinstitute/imaging-bbbc#84]
- [x] Update [contribute](https://data.broadinstitute.org/bbbc/contribute.html) to reflect Google form submission process 
- [x] Update Image Sets page to include all types of Ground Truth: it is missing Bounding Boxes (U)

**Comment by bledford87** [comment]
Contribute: https://bbbc.broadinstitute.org/contribute
Benchmarking: https://bbbc.broadinstitute.org/benchmarking#Bounding
