### ISSUE TITLE
Revive BBBC025

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/imaging-bbbc#97]
@bethac07 said

> So it looks like the [BBBC025](https://bbbc.broadinstitute.org/BBBC025) images were accidentally deleted from having a Broad-local-copy; briefly, their folder in /imaging/web/BBBC/high_throughput_images/ was just a softlink to a folder on /imaging/docs, so when that got deleted, there was no longer a local copy. Luckily, it looks like the folder the soft link went to was tarballed back in 2018 and put on imaging cold, so it will be easy to retrieve those images.

Ah yes, now I recollect – indeed, it was archived to https://imaging-platform-cold.s3.amazonaws.com/imaging_docs/PD.tar.gz (ideally, I should have synced it *somewhere* before archiving :D)

> My question - do we want to just put them in BBBC, or do we want to put them in the Gallery and have BBBC link to them from there?

I do think it makes sense to store BBBC025 on the gallery; I can tag team with whoever is going to unarchive it (Barbara?) I've initiated the restore

https://github.com/broadinstitute/cellpainting-gallery/issues/18

**Comment by bethac07** [comment]
How long is it restored for? Barbara may be intermittently out for the rest of the week, so if it's just a matter of "unzip a tarball, sync images onto the gallery folder", I can definitely take care of that.

**Comment by shntnu** [comment]
1 week 

But no hurry (at least from my end)

**Comment by bethac07** [comment]
Started a tiny EC2 instance downloading the tarball, just so we don't have to deal with a re-restore. @bdiazroh we can chat tomorrow about next steps.

**Comment by bethac07** [comment]
@shntnu : @bdiazroh has rescued the files and is short-term going to download them to /imaging/web . We can delete them from there once they're nicely settled in the gallery.

Longer term, I assume we want to undo the current structure (per-plate/per-channel individual tarballs) to be something more like a normal structure before they go in the gallery?

**Comment by shntnu** [comment]
> @shntnu : @bdiazroh has rescued the files and is short-term going to download them to /imaging/web . We can delete them from there once they're nicely settled in the gallery.

🎉 

> Longer term, I assume we want to undo the current structure (per-plate/per-channel individual tarballs) to be something more like a normal structure before they go in the gallery?

Yes, please. Perhaps we could head over to https://github.com/broadinstitute/cellpainting-gallery/issues/18 to make we satisfy the Weisbart conditions?

**Comment by shntnu** [comment]
I am closing this out in favor of https://github.com/broadinstitute/cellpainting-gallery/issues/18
